# Generated by Django 2.1.7 on 2019-09-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('email', models.CharField(max_length=8, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=10)),
                ('reg_created_at', models.DateTimeField(auto_now_add=True)),
                ('reg_modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registration_form',
            },
        ),
    ]
