# Generated by Django 2.1.7 on 2019-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
