# Generated by Django 2.1.7 on 2019-10-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
