# Generated by Django 2.1.7 on 2019-10-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
