# Generated by Django 2.1.7 on 2019-10-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
