# Generated by Django 2.1.7 on 2019-10-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_userprofile_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signupinfo',
            table='user_signup',
        ),
    ]
